/**
 * `pnpm --filter @lawmind/ingest coverage:cells [--apply] [--frontier <path>]`
 *
 * Fills `coverage_cell` (migration 0059) — the precomputed court × year table the
 * retrieval path reads instead of recomputing coverage per request.
 *
 * **DRY BY DEFAULT.** `--apply` writes.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * IT READS ARTEFACTS FOR ONE AXIS AND THE DATABASE FOR THE OTHER, ON PURPOSE
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * ACQUISITION comes from NEW2's `new2-frontier.json`: source rows per cell from
 * `HC_METADATA_SURVEY`, held per cell from an exact `count(*)` NEW2 already ran.
 * Recomputing held here would be a second sequential scan of 18.6M judgments to
 * learn what the lane that owns ingestion measured an hour ago. It also carries
 * `heldFreshness`, which this reproduces rather than flattening: when a worker
 * wrote after the held snapshot, every `acquired` is a LOWER bound and the cell
 * can read as a gap that has since been filled.
 *
 * REACHABILITY is measured here because no artefact carries it. It is the union
 * of two populations and both are small: `judgment_chunks` (40,161 distinct
 * judgments, the frozen chunk architecture) and `new1_doc_vector_stage` (NEW1's
 * Tier-A document vectors). Around 150k primary-key lookups against `judgments`,
 * not a scan.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * THE COURT KEY IS A CODE ON ONE SIDE AND A NAME ON THE OTHER
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * `judgments.court` holds a NAME; the frontier is keyed by the survey CODE.
 * `HC_METADATA_SURVEY.json`'s `perCourt` is the join, exactly as
 * `new2-held-refresh.mjs` uses it. The Supreme Court has judgments and no survey
 * code — it is not a High Court and the survey does not cover it — so its cells
 * carry `source_state = 'UNKNOWN'` rather than being dropped or, worse, counted
 * as a gap against a denominator that does not exist.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * NO THRESHOLD IS APPLIED HERE EITHER
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * `PARTIAL` is "held some, not all" and nothing more. Where partial becomes
 * *"too little to be an answer"* is a product judgement (`PRODUCT_DECISIONS.md`),
 * and `held_share` is written so that policy can be applied later without
 * recomputing anything.
 */
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { openDb } from './db-host.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const arg = (name: string, fallback: string): string => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1]! : fallback;
};
const APPLY = process.argv.includes('--apply');
const FRONTIER = arg('frontier', join(ROOT, 'docs', 'ops', 'migration', 'new2-frontier.json'));
const SURVEY = arg('survey', join(ROOT, 'docs', 'HC_METADATA_SURVEY.json'));

const dbUrl = process.env['CORPUS_DATABASE_URL'] ?? process.env['DATABASE_URL'];
if (!dbUrl) {
  console.error('DATABASE_URL is not set. Run with `npx tsx --env-file=.env`.');
  process.exit(2);
}

type FrontierCell = {
  court: string;
  year: number;
  sourceRows: number;
  acquired: number;
  state?: string;
  /** Source rows walked that yielded no document because the source has no PDF. */
  permanentAbsent?: number;
  /** Transient failures. These will close. */
  retryable?: number;
};
type Frontier = {
  takenAt: string;
  derivedFrom?: { source?: string; held?: string };
  heldFreshness?: { heldTakenAt?: string; heldIsStale?: boolean };
  cells: FrontierCell[];
};

const frontier = JSON.parse(readFileSync(FRONTIER, 'utf8')) as Frontier;
const survey = JSON.parse(readFileSync(SURVEY, 'utf8')) as {
  perCourt?: { name: string; code: string }[];
  perCourtPerYear?: Record<string, Record<string, number>>;
};
const nameByCode = new Map((survey.perCourt ?? []).map((c) => [c.code, c.name]));

/**
 * The `bench=testcase` subtraction, VERIFIED here rather than trusted upstream.
 *
 * `HC_METADATA_SURVEY.perCourtPerYear` sums parquet footers with no bench
 * breakdown, so it counts a published test fixture that `hc-load.ts`
 * `isTestFixture()` refuses by rule — 289,502 rows across 44 Bombay cells
 * (NEW2, bus 0887). A denominator carrying those reports a court as short of
 * law by rows that are not law and that we correctly never fetched.
 *
 * NEW2's `new2-frontier.mjs` already subtracts it. **This file re-derives the
 * arithmetic anyway and refuses to write a cell where the frontier's denominator
 * does not equal `raw − excluded`.** Not distrust of that lane: the artefact is
 * regenerated by a different tool on a different cadence, and an exclusion
 * silently dropped from a future regeneration would look exactly like a court
 * that had grown. A check that only fires when something is wrong costs nothing
 * on every run where nothing is.
 */
const EXCLUSIONS = arg(
  'exclusions',
  join(ROOT, 'docs', 'ops', 'migration', 'new2-source-exclusions.json'),
);
const exclusions = JSON.parse(readFileSync(EXCLUSIONS, 'utf8')) as {
  totalRows?: number;
  byCourtCodeByYear?: Record<string, Record<string, number>>;
};
const excludedFor = (code: string, year: number): number =>
  Number(exclusions.byCourtCodeByYear?.[code]?.[String(year)] ?? 0);
const rawSourceFor = (code: string, year: number): number | null => {
  const name = nameByCode.get(code);
  if (!name) return null;
  const v = survey.perCourtPerYear?.[name]?.[String(year)];
  return typeof v === 'number' ? v : null;
};

/**
 * Which courts' source counts are known to count LISTINGS rather than documents.
 *
 * Allahabad 2018 reads 456,951 source rows against 228,653 documents — a ratio
 * of 1.998 — and 2019 reads 1.988. **A coverage figure does not land on 50.0%
 * twice.** Those cells are `WALKED` with `remainingRows: 0`, so every source row
 * was visited, and the court's whole ingest ledger holds 22,407 failures; half a
 * million walked rows produced no document and no failure, which leaves only
 * rows for documents already held. Migration 0059's header named the same cause
 * from the other direction.
 *
 * A cell flagged here still reports its `held_share`. The flag does not make a
 * gap disappear — it is what stops the share being read as a share of the law.
 *
 * **Threshold, not a list of courts, would be wrong here.** A ratio near 2.0 is
 * evidence of duplication only in combination with a walked cursor and an empty
 * failure ledger; inferring it from the ratio alone would silence real gaps in
 * courts nobody has checked. So this is an explicit, evidenced enumeration and
 * a court joins it only after the same three facts are established for it.
 */
const DENOMINATOR_SUSPECT_COURTS = new Set(['9_13']);

/**
 * `SOURCE_HAS_ZERO` requires a POSITIVE measurement of zero — a cell the survey
 * counted and found empty. A cell the survey never counted is `UNKNOWN`, and the
 * difference is the whole reason the state exists: inferring "the source has
 * nothing" from "we found nothing" is the failure it reports.
 */
function sourceState(sourceRows: number | null, held: number): string {
  if (sourceRows === null) return 'UNKNOWN';
  if (sourceRows === 0) return 'SOURCE_HAS_ZERO';
  if (held === 0) return 'KNOWN_GAP';
  return held >= sourceRows ? 'COVERED' : 'PARTIAL';
}

/**
 * WHY a cell is short — orthogonal to `sourceState`, which says WHETHER.
 *
 * Measured 20 Aug 2026: of 257 cells carrying a shortfall, **179 have a
 * shortfall that is entirely `permanentAbsent` + `retryable`**. Bombay 2006 is
 * short 6,276 with 6,275 permanently absent; Bombay 2007 is short 6,706 with
 * 6,706 permanently absent, exactly. Every one of those reads `PARTIAL` — *"we
 * are missing law"* — about documents the court never published. That is
 * precisely the confusion migration 0059 exists to prevent, and it arrived
 * through a column that was never added rather than through the state machine.
 *
 * `DENOMINATOR_SUSPECT` is checked FIRST because it is a statement about our own
 * number, and a cell whose denominator is not a document count cannot have its
 * residue attributed at all — calling that residue `UNEXPLAINED` would imply we
 * had looked for law and not found it.
 *
 * `UNEXPLAINED` is the default and is **not** a failure state. It means the
 * residue has not been attributed yet. Same discipline as `UNKNOWN` on the
 * acquisition axis: an unmeasured thing must never inherit a confident label.
 */
function shortfallReason(
  courtCode: string,
  sourceRows: number | null,
  held: number,
  permanentAbsent: number,
  retryable: number,
): { reason: string; unexplained: number | null } {
  if (sourceRows === null || sourceRows <= 0) return { reason: 'UNEXPLAINED', unexplained: null };
  const shortfall = sourceRows - held;
  if (shortfall <= 0) return { reason: 'NONE', unexplained: 0 };
  const unexplained = Math.max(0, shortfall - permanentAbsent - retryable);
  if (DENOMINATOR_SUSPECT_COURTS.has(courtCode))
    return { reason: 'DENOMINATOR_SUSPECT', unexplained };
  if (unexplained === 0) {
    if (retryable === 0) return { reason: 'SOURCE_ABSENT', unexplained: 0 };
    if (permanentAbsent === 0) return { reason: 'RETRYABLE', unexplained: 0 };
    return { reason: 'PARTLY_EXPLAINED', unexplained: 0 };
  }
  if (permanentAbsent + retryable > 0) return { reason: 'PARTLY_EXPLAINED', unexplained };
  return { reason: 'UNEXPLAINED', unexplained };
}

const sql = await openDb(dbUrl, 2);

try {
  // Reachability: every judgment carrying ANY vector, by court and year. The two
  // populations are unioned because either one makes a document reachable by the
  // dense arm, and a document can be in both.
  console.log('counting reachable documents (judgment_chunks ∪ new1_doc_vector_stage) …');
  const embeddedRows = await sql<{ court: string | null; year: number | null; n: number }[]>`
    WITH embedded AS (
      SELECT DISTINCT judgment_id FROM judgment_chunks
      UNION
      SELECT DISTINCT judgment_id FROM new1_doc_vector_stage
    )
    SELECT j.court, EXTRACT(YEAR FROM j.judgment_date)::int AS year, count(*)::int AS n
      FROM embedded e
      JOIN judgments j ON j.id = e.judgment_id
     GROUP BY 1, 2`;
  const embeddedBy = new Map(embeddedRows.map((r) => [`${r.court ?? ''}|${r.year ?? 0}`, r.n]));
  const embeddedTotal = embeddedRows.reduce((a, r) => a + r.n, 0);
  console.log(
    `  ${embeddedTotal.toLocaleString()} reachable documents over ${embeddedRows.length} court-year cells`,
  );

  // Tier-A eligibility per cell, from the census the embed lane already ran.
  const eligibleRows = await sql<
    { court: string | null; judgment_year: number | null; n: string }[]
  >`
    SELECT court, judgment_year, sum(rows)::text AS n
      FROM embedding_census_cell
     WHERE bucket LIKE 'tier_a%'
     GROUP BY 1, 2`;
  const eligibleBy = new Map(
    eligibleRows.map((r) => [`${r.court ?? ''}|${r.judgment_year ?? 0}`, Number(r.n)]),
  );

  const heldMeasuredAt = frontier.heldFreshness?.heldTakenAt ?? frontier.takenAt;
  const provenance = frontier.derivedFrom?.source ?? 'new2-frontier.json';

  type Upsert = {
    court: string;
    year: number;
    sourceRows: number | null;
    sourceRowsRaw: number | null;
    sourceExcluded: number | null;
    held: number;
    heldShare: number | null;
    state: string;
    permanentAbsent: number | null;
    retryable: number | null;
    unexplained: number | null;
    shortfallReason: string;
    embedded: number;
    eligible: number | null;
    reachability: string;
  };
  const upserts: Upsert[] = [];
  const unjoined = new Set<string>();
  /** Cells where the frontier's denominator does not equal `raw − excluded`. */
  const exclusionDrift: string[] = [];

  for (const cell of frontier.cells) {
    const court = nameByCode.get(cell.court);
    if (!court) {
      unjoined.add(cell.court);
      continue;
    }
    const key = `${court}|${cell.year}`;
    const embedded = embeddedBy.get(key) ?? 0;
    const held = cell.acquired ?? 0;
    const sourceRows = typeof cell.sourceRows === 'number' ? cell.sourceRows : null;

    // Re-derive the fixture subtraction rather than trusting it. See EXCLUSIONS.
    const raw = rawSourceFor(cell.court, cell.year);
    const excluded = excludedFor(cell.court, cell.year);
    if (raw !== null && sourceRows !== null && raw - excluded !== sourceRows) {
      exclusionDrift.push(
        `${court} ${cell.year}: raw ${raw} − excluded ${excluded} = ${raw - excluded}, frontier says ${sourceRows}`,
      );
    }

    const permanentAbsent = cell.permanentAbsent ?? 0;
    const retryable = cell.retryable ?? 0;
    const { reason, unexplained } = shortfallReason(
      cell.court,
      sourceRows,
      held,
      permanentAbsent,
      retryable,
    );

    upserts.push({
      court,
      year: cell.year,
      sourceRows,
      sourceRowsRaw: raw,
      sourceExcluded: raw === null ? null : excluded,
      held,
      heldShare: sourceRows && sourceRows > 0 ? Number((held / sourceRows).toFixed(6)) : null,
      state: sourceState(sourceRows, held),
      permanentAbsent,
      retryable,
      unexplained,
      shortfallReason: reason,
      embedded,
      eligible: eligibleBy.get(key) ?? null,
      reachability: embedded > 0 ? 'EMBEDDED' : 'LEXICAL_ONLY',
    });
  }

  /**
   * Cells the survey does not cover — the Supreme Court, which is not a High
   * Court — still get a row, because a cell that is absent from this table reads
   * as "nobody has measured it" through the same UNKNOWN default and the caller
   * cannot tell the two apart. Written explicitly with a null denominator.
   */
  for (const [key, embedded] of embeddedBy) {
    const [court, yearText] = key.split('|');
    if (!court || !yearText) continue;
    const year = Number(yearText);
    if (!year) continue;
    if (upserts.some((u) => u.court === court && u.year === year)) continue;
    upserts.push({
      court,
      year,
      sourceRows: null,
      sourceRowsRaw: null,
      sourceExcluded: null,
      held: 0,
      heldShare: null,
      state: 'UNKNOWN',
      // No denominator, so no shortfall to attribute. UNEXPLAINED is honest
      // here in the same sense UNKNOWN is: nothing has been measured, and
      // NONE would assert there is nothing to find.
      permanentAbsent: null,
      retryable: null,
      unexplained: null,
      shortfallReason: 'UNEXPLAINED',
      embedded,
      eligible: eligibleBy.get(key) ?? null,
      reachability: embedded > 0 ? 'EMBEDDED' : 'LEXICAL_ONLY',
    });
  }

  const byState = new Map<string, number>();
  for (const u of upserts) byState.set(u.state, (byState.get(u.state) ?? 0) + 1);
  const byReason = new Map<string, number>();
  for (const u of upserts)
    byReason.set(u.shortfallReason, (byReason.get(u.shortfallReason) ?? 0) + 1);
  const reachable = upserts.filter((u) => u.reachability === 'EMBEDDED').length;

  console.log(`\ncells ${upserts.length}`);
  for (const [state, n] of [...byState].sort((a, b) => b[1] - a[1]))
    console.log(`  ${state.padEnd(16)} ${n}`);
  console.log('\nwhy the short cells are short:');
  for (const [reason, n] of [...byReason].sort((a, b) => b[1] - a[1]))
    console.log(`  ${reason.padEnd(20)} ${n}`);
  const sum = (f: (u: Upsert) => number | null): number =>
    upserts.reduce((a, u) => a + (f(u) ?? 0), 0);
  console.log(
    `  rows: permanent_absent ${sum((u) => u.permanentAbsent).toLocaleString()} · ` +
      `retryable ${sum((u) => u.retryable).toLocaleString()} · ` +
      `unexplained ${sum((u) => u.unexplained).toLocaleString()} · ` +
      `source_excluded ${sum((u) => u.sourceExcluded).toLocaleString()}`,
  );
  console.log(
    `  reachability     EMBEDDED ${reachable} · LEXICAL_ONLY ${upserts.length - reachable}`,
  );
  if (unjoined.size > 0)
    console.log(`  survey codes with no court name: ${[...unjoined].join(', ')}`);

  /**
   * The fixture subtraction is arithmetic, so a mismatch is a real defect in an
   * input and not a judgement call. Refuse the write rather than persist a
   * denominator nobody can reproduce — a wrong coverage number is worse than a
   * stale one, because staleness is visible in `source_measured_at` and
   * wrongness is not.
   */
  if (exclusionDrift.length > 0) {
    console.error(
      `\nREFUSING TO WRITE — ${exclusionDrift.length} cell(s) where the frontier's ` +
        'denominator does not equal raw − excluded. The exclusion join has drifted ' +
        'from the survey it was computed against:',
    );
    for (const d of exclusionDrift.slice(0, 10)) console.error(`  ${d}`);
    if (exclusionDrift.length > 10) console.error(`  … and ${exclusionDrift.length - 10} more`);
    process.exitCode = 1;
  } else {
    console.log(
      `  exclusion join verified: raw − excluded matches the frontier on every joined cell ` +
        `(${(exclusions.totalRows ?? 0).toLocaleString()} fixture rows subtracted)`,
    );
  }
  if (frontier.heldFreshness?.heldIsStale) {
    console.log(
      '  held is STALE — a worker wrote after the snapshot, so every held count is a LOWER bound',
    );
  }

  if (exclusionDrift.length > 0) {
    console.log('\nNothing written — fix the exclusion drift above first.');
  } else if (!APPLY) {
    console.log('\nNothing written — re-run with --apply.');
  } else {
    for (const u of upserts) {
      await sql`
        INSERT INTO coverage_cell (court, year, source_rows, source_rows_raw, source_excluded,
                                   source_provenance, source_measured_at,
                                   held, held_measured_at, held_share, source_state,
                                   permanent_absent, retryable, unexplained, shortfall_reason,
                                   embedded, eligible, embedded_measured_at, reachability, updated_at)
        VALUES (${u.court}, ${u.year}, ${u.sourceRows}, ${u.sourceRowsRaw}, ${u.sourceExcluded},
                ${provenance}, ${frontier.takenAt}::timestamptz,
                ${u.held}, ${heldMeasuredAt}::timestamptz, ${u.heldShare}, ${u.state},
                ${u.permanentAbsent}, ${u.retryable}, ${u.unexplained}, ${u.shortfallReason},
                ${u.embedded}, ${u.eligible}, now(), ${u.reachability}, now())
        ON CONFLICT (court, year) DO UPDATE SET
          source_rows = EXCLUDED.source_rows,
          source_rows_raw = EXCLUDED.source_rows_raw,
          source_excluded = EXCLUDED.source_excluded,
          source_provenance = EXCLUDED.source_provenance,
          source_measured_at = EXCLUDED.source_measured_at,
          held = EXCLUDED.held,
          held_measured_at = EXCLUDED.held_measured_at,
          held_share = EXCLUDED.held_share,
          source_state = EXCLUDED.source_state,
          permanent_absent = EXCLUDED.permanent_absent,
          retryable = EXCLUDED.retryable,
          unexplained = EXCLUDED.unexplained,
          shortfall_reason = EXCLUDED.shortfall_reason,
          embedded = EXCLUDED.embedded,
          eligible = EXCLUDED.eligible,
          embedded_measured_at = EXCLUDED.embedded_measured_at,
          reachability = EXCLUDED.reachability,
          updated_at = now()`;
    }
    console.log(`\nWrote ${upserts.length} cells.`);
  }
} finally {
  await sql.end();
}
