#!/usr/bin/env node
/**
 * The local PostgreSQL cluster — configure, start, stop, and switch it between
 * restore mode and serving mode.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY A SCRIPT RATHER THAN "I ran some commands once"
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * This cluster IS the data moat after cutover. Railway is being shut down, so
 * there is no longer a managed service that remembers how the database was set
 * up. Every setting has to be reproducible from the repository, because the
 * alternative is a 104 GB database whose configuration exists only as shell
 * history on one Windows machine.
 *
 * The tuning itself lives in `docs/ops/migration/lawmind.conf`, with the
 * reasoning attached to each value. This script installs it as an include and
 * never edits `postgresql.conf`'s own lines — so the cluster's defaults stay
 * visible and the LawMind overrides stay in one reviewable file.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * COMMANDS
 * ─────────────────────────────────────────────────────────────────────────────
 *
 *   configure     install the include + pg_hba, idempotent
 *   start | stop | restart | status
 *   restore-mode  synchronous_commit=off, autovacuum off — RESTORE ONLY
 *   serve-mode    the durable settings; run before cutover
 *   createdb      create the lawmind database with the right locale + extensions
 *   psql ...      pass through to the local cluster, credentials handled
 *
 * `restore-mode` exists because the two workloads want opposite things and
 * saying so in one place beats remembering. During a restore every byte is
 * reproducible from the archive on disk, so durability buys nothing and costs
 * hours. After cutover the opposite is true and it is the whole moat.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync, spawn } from 'node:child_process';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

export const PG = {
  home: process.env.LAWMIND_PG_HOME ?? 'C:\\lawmind',
  bin: process.env.LAWMIND_PG_BIN ?? 'C:\\lawmind\\pgsql\\pgsql\\bin',
  data: process.env.LAWMIND_PG_DATA ?? 'C:\\lawmind\\pgdata',
  logs: process.env.LAWMIND_PG_LOGS ?? 'C:\\lawmind\\logs',
  dump: process.env.LAWMIND_PG_DUMP_DIR ?? 'C:\\lawmind\\dump',
  port: Number(process.env.LAWMIND_PG_PORT ?? 5432),
  superuser: 'postgres',
  database: process.env.LAWMIND_PG_DATABASE ?? 'lawmind',
};

const exe = (name) => path.join(PG.bin, `${name}.exe`);

/** The superuser password, generated by initdb time and kept out of the repo. */
export function pgPassword() {
  const f = path.join(PG.home, '.pgpass_init');
  if (!fs.existsSync(f)) throw new Error(`No password file at ${f}. Was initdb run?`);
  return fs.readFileSync(f, 'utf8').trim();
}

/** Environment for every libpq child process. PGPASSWORD never hits a log line. */
export function pgEnv(extra = {}) {
  return {
    ...process.env,
    PGPASSWORD: pgPassword(),
    PGHOST: '127.0.0.1',
    PGPORT: String(PG.port),
    PGUSER: PG.superuser,
    // Windows console defaults to a legacy code page; libpq client tools then
    // mangle every non-ASCII byte on the way out. The corpus is Devanagari in
    // places, so this is not cosmetic.
    PGCLIENTENCODING: 'UTF8',
    ...extra,
  };
}

export function run(cmd, args, { env, cwd, quiet } = {}) {
  const r = spawnSync(cmd, args, {
    env: env ?? pgEnv(),
    cwd,
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024,
    windowsHide: true,
  });
  if (!quiet) {
    if (r.stdout?.trim()) process.stdout.write(r.stdout);
    if (r.stderr?.trim()) process.stderr.write(r.stderr);
  }
  return r;
}

/** One-shot SQL against the local cluster. Returns trimmed stdout. */
export function psqlValue(sql, db = 'postgres') {
  const r = run(exe('psql'), ['-d', db, '-t', '-A', '-X', '-q', '-c', sql], { quiet: true });
  if (r.status !== 0) throw new Error(`psql failed: ${r.stderr || r.stdout}`);
  return (r.stdout ?? '').trim();
}

export function psqlExec(sql, db = 'postgres') {
  const r = run(exe('psql'), ['-d', db, '-X', '-q', '-v', 'ON_ERROR_STOP=1', '-c', sql]);
  if (r.status !== 0) throw new Error(`psql failed (${r.status})`);
}

// ─────────────────────────────────────────────────────────────────────────────
// configure
// ─────────────────────────────────────────────────────────────────────────────
const INCLUDE_MARK = "include = 'lawmind.conf'";

function configure() {
  fs.mkdirSync(PG.logs, { recursive: true });
  fs.mkdirSync(PG.dump, { recursive: true });

  const src = path.join(REPO_ROOT, 'docs', 'ops', 'migration', 'lawmind.conf');
  const dst = path.join(PG.data, 'lawmind.conf');
  fs.copyFileSync(src, dst);
  console.log(`configure: copied ${src} -> ${dst}`);

  const mainConf = path.join(PG.data, 'postgresql.conf');
  let text = fs.readFileSync(mainConf, 'utf8');
  if (!text.includes(INCLUDE_MARK)) {
    text +=
      '\n\n# ── LawMind ────────────────────────────────────────────────────────\n' +
      '# Tuning lives in lawmind.conf, copied from docs/ops/migration/lawmind.conf\n' +
      '# by scripts/migration/pg-local.mjs. Edit the repo copy, then re-run\n' +
      '# `node scripts/migration/pg-local.mjs configure && ... restart`.\n' +
      `${INCLUDE_MARK}\n`;
    fs.writeFileSync(mainConf, text);
    console.log('configure: added include to postgresql.conf');
  } else {
    console.log('configure: include already present');
  }

  // pg_hba: initdb leaves host connections on trust. This cluster holds the
  // whole corpus and, after cutover, the only copy of the enrichment work.
  // scram-sha-256, loopback only. No `host all all 0.0.0.0/0` line exists and
  // none is ever added — the founder directive says PostgreSQL is not published.
  const hba = path.join(PG.data, 'pg_hba.conf');
  const desired = [
    '# LawMind — written by scripts/migration/pg-local.mjs.',
    '# Loopback only, password authentication. PostgreSQL is NEVER published;',
    '# external access goes through cloudflared to the HTTP API, not to 5432.',
    '# TYPE  DATABASE  USER  ADDRESS         METHOD',
    'host    all       all   127.0.0.1/32    scram-sha-256',
    'host    all       all   ::1/128         scram-sha-256',
    '',
  ].join('\n');
  fs.writeFileSync(hba, desired);
  console.log('configure: pg_hba.conf set to scram-sha-256 on loopback only');
}

// ─────────────────────────────────────────────────────────────────────────────
// lifecycle
// ─────────────────────────────────────────────────────────────────────────────
function isRunning() {
  const r = run(exe('pg_ctl'), ['-D', PG.data, 'status'], { quiet: true });
  return r.status === 0;
}

const TASK_NAME = 'LawMindPostgres';

/**
 * ─────────────────────────────────────────────────────────────────────────────
 * WHY THE POSTMASTER IS SPAWNED DIRECTLY AND NEVER THROUGH `pg_ctl start`
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * `0xC000013A` is `STATUS_CONTROL_C_EXIT` — a **console control event**, not a
 * crash, not memory corruption, and nothing to do with the workload. Windows
 * delivers it to every process attached to a console when that console goes
 * away. This cluster was hit four times, and the ingest fleet lost all 38
 * workers to the identical code on 15 Aug.
 *
 * The earlier version of this file blamed `spawn(..., { detached: true })` and
 * moved the start to Task Scheduler. **The diagnosis was one level off**, which
 * is why the crashes continued from inside a scheduled task. The real mechanism,
 * read off the live server (NEW2, bus 0597) rather than reasoned about:
 *
 *   postmaster pid 27764
 *   parent pid 6848, ALIVE:
 *     cmd.exe /C ""C:/lawmind/pgsql/pgsql/bin/postgres.exe" -D "C:/lawmind/pgdata"
 *              < "nul" >> "C:\lawmind\logs\pg_ctl.log" 2>&1"
 *
 * `pg_ctl start` on Windows shells out through `cmd.exe`. **The postmaster
 * therefore inherits that cmd.exe's console, and every backend and background
 * worker it forks inherits it too.** `detached: true` was never the problem —
 * it was applied to `pg_ctl`, a launcher that exits, while the `cmd.exe` it
 * spawned re-acquired a console for the server that outlives it. Task Scheduler
 * did not help for the same reason: it removed the console from `pg_ctl`, and
 * `pg_ctl` promptly made a new one via `cmd.exe`.
 *
 * So the fix is to **cut `pg_ctl` and its `cmd.exe` out of the start path
 * entirely** and spawn `postgres.exe` itself with `detached: true`. libuv maps
 * that to `DETACHED_PROCESS` on Windows, which means the child inherits no
 * console AND is given no new one — there is nothing left to signal.
 *
 * MEASURED, with a control that discriminates rather than a claim that sounds
 * right. Two identical children, one flag apart, launched from a harness tool
 * call and checked from a later one — i.e. across exactly the console teardown
 * that does the killing:
 *
 *   detached: true   -> ALIVE, still heartbeating
 *   detached: false  -> DEAD
 *
 * `logging_collector = on` (lawmind.conf), so the syslogger captures the
 * server's own log regardless. stdio is still pointed at `pg_ctl.log` rather
 * than `'ignore'`, because the errors that happen BEFORE the collector starts —
 * a bad config line, a stale lock file — are exactly the ones worth having, and
 * `'ignore'` would drop them on the floor.
 *
 * THIS IS THE INTERIM, NOT THE FIX. A Windows service runs with no console at
 * all and starts without anyone being logged in; `DETACHED_PROCESS` only removes
 * the console binding. FQ-PGSERVICE holds the one elevated command that ends
 * this properly, and it stays open until the founder runs it.
 */
function spawnPostmaster() {
  const log = path.join(PG.logs, 'pg_ctl.log');
  fs.mkdirSync(PG.logs, { recursive: true });
  const fd = fs.openSync(log, 'a');
  const child = spawn(exe('postgres'), ['-D', PG.data], {
    env: pgEnv(),
    detached: true,
    stdio: ['ignore', fd, fd],
    windowsHide: true,
  });
  child.unref();
  fs.closeSync(fd);
  return child.pid;
}

function ensureTask() {
  const q = run('schtasks.exe', ['/query', '/tn', TASK_NAME], { env: process.env, quiet: true });
  if (q.status === 0) return false;

  const log = path.join(PG.logs, 'pg_ctl.log');
  // `schtasks /create /sc ONLOGON` is refused unelevated ("ERROR: Access is
  // denied"), but the PowerShell scheduled-task cmdlets create the same
  // ONLOGON task for the current user without elevation. Tried in that order
  // rather than assumed — the schtasks refusal is what sent us here.
  //
  // ExecutionTimeLimit = 0 means "no limit". The default kills a task after
  // three days, and this one is meant to run for as long as the machine is up.
  const ps = [
    // The action is THIS SCRIPT's `spawn-detached`, never `pg_ctl start`. See
    // spawnPostmaster(): pg_ctl shells through cmd.exe and hands the postmaster
    // a console, which is the thing that kills it. Task Scheduler removes the
    // console from whatever it launches, but it cannot stop pg_ctl making a new
    // one, so the task has to launch a starter that does not.
    //
    // This also retires the `-t 120`/`-t 600` question NEW2 found in bus 0585:
    // pg_ctl's `-w` timeout reported FAILURE on a start that had succeeded,
    // because crash recovery here measured 150.9s. There is no `-w` on this
    // path at all — nothing waits, so nothing can time out and mislabel a good
    // start as a bad one. Readiness is established by connecting, below.
    `$a = New-ScheduledTaskAction -Execute '${process.execPath}' -Argument '"${path.join(REPO_ROOT, 'scripts', 'migration', 'pg-local.mjs')}" spawn-detached' -WorkingDirectory '${REPO_ROOT}'`,
    `$t = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\\$env:USERNAME"`,
    `$s = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -ExecutionTimeLimit ([TimeSpan]::Zero) -StartWhenAvailable`,
    `Register-ScheduledTask -TaskName '${TASK_NAME}' -Action $a -Trigger $t -Settings $s -RunLevel Limited -Force | Out-Null`,
  ].join('; ');

  const r = run('powershell.exe', ['-NoProfile', '-NonInteractive', '-Command', ps], {
    env: process.env,
    quiet: true,
  });
  if (r.status !== 0) {
    console.error(`start: could not create scheduled task ${TASK_NAME}`);
    console.error(r.stderr || r.stdout);
    console.error('  Falling back to a detached spawn — BUT SEE THE COMMENT ABOVE:');
    console.error('  a spawned server is killed by console signals and will not survive a long restore.');
    return null;
  }
  console.log(`start: created scheduled task ${TASK_NAME} (also starts the cluster at logon)`);
  return true;
}

function sleepMs(ms) {
  // No async here on purpose: start() is called from a synchronous command
  // dispatcher and a busy-wait on a child process keeps the control flow plain.
  spawnSync(process.execPath, ['-e', `setTimeout(()=>{},${ms})`], { timeout: ms + 2000 });
}

function start() {
  // Boot persistence is checked BEFORE the already-running short-circuit, on
  // purpose. A running cluster with no auto-start looks completely healthy and
  // is one reboot from being down, so `start` on a live server must still be
  // able to notice the task is missing — which is the exact state this machine
  // was found in on 17 Aug: 12 postgres processes up, 0 tasks, 0 services.
  ensureTask();
  if (isRunning()) {
    console.log('start: already running');
    return;
  }
  const log = path.join(PG.logs, 'pg_ctl.log');

  // Started here, in-process, by the same console-free mechanism the task uses.
  // Not `schtasks /run`: that would make every manual start depend on the task
  // existing, and the task is precisely the artifact that has gone missing twice.
  const pid = spawnPostmaster();
  console.log(`start: postmaster spawned detached, pid ${pid} (no console, no cmd.exe parent)`);

  // 600s, not 120s. Crash recovery on this cluster has MEASURED 150.9s replaying
  // a 22 GB WAL (NEW2, bus 0585), and the old 120s ceiling turned a successful
  // start into a reported failure. Waiting is free; a false failure is not.
  const deadline = Date.now() + 600_000;
  let announcedRecovery = false;
  while (Date.now() < deadline) {
    // `pg_isready`, not `pg_ctl status`. The postmaster process exists for the
    // whole of crash recovery, so `status` says "running" while every connection
    // is still refused — which is how a 150s recovery reads as an instant start
    // followed by an inexplicable ECONNREFUSED in whatever runs next.
    if (run(exe('pg_isready'), ['-q'], { quiet: true }).status === 0) {
      console.log(`start: accepting connections on 127.0.0.1:${PG.port}`);
      return;
    }
    if (!announcedRecovery && isRunning()) {
      console.log('start: postmaster up, not yet accepting connections (crash recovery replays WAL; measured 150.9s here)');
      announcedRecovery = true;
    }
    sleepMs(1000);
  }
  console.error(`start: did not accept connections within 600s. See ${log} and ${path.join(PG.data, 'log')}`);
  process.exit(1);
}

function stop() {
  if (!isRunning()) {
    console.log('stop: not running');
    return;
  }
  // `fast` rolls back open transactions and shuts down promptly. `smart` waits
  // for every client to disconnect, which on this machine means waiting for
  // whatever forgot to close its pool.
  const r = run(exe('pg_ctl'), ['-D', PG.data, '-m', 'fast', '-w', '-t', '120', 'stop']);
  if (r.status !== 0) process.exit(1);
}

// ─────────────────────────────────────────────────────────────────────────────
// modes
// ─────────────────────────────────────────────────────────────────────────────
const RESTORE_SETTINGS = {
  // Every byte is reproducible from the archive on disk during a restore, so
  // fsync-per-commit buys nothing and costs hours.
  synchronous_commit: 'off',
  // Autovacuum during a bulk load competes for exactly the IO the load needs,
  // and vacuums tables that are about to grow tenfold. ANALYZE runs once at the
  // end instead — see restore.mjs.
  autovacuum: 'off',
  // Bulk COPY generates WAL faster than any normal workload.
  max_wal_size: '32GB',
  checkpoint_timeout: '60min',
  // pg_restore --jobs workers each build indexes; give them room — but this is
  // PER WORKER, and this machine's binding constraint is the Windows commit
  // limit, not RAM (see lawmind.conf, shared_buffers). 4 jobs x 1 GB = 4 GB.
  maintenance_work_mem: '1GB',
};

const SERVE_SETTINGS = {
  synchronous_commit: 'on',
  autovacuum: 'on',
  max_wal_size: '16GB',
  checkpoint_timeout: '30min',
  maintenance_work_mem: '512MB',
};

function applySettings(map, label) {
  for (const [k, v] of Object.entries(map)) {
    psqlExec(`ALTER SYSTEM SET ${k} = '${v}'`);
  }
  psqlExec('SELECT pg_reload_conf()');
  console.log(`${label}: applied ${Object.keys(map).length} settings via ALTER SYSTEM + reload`);
  // Two of these need a restart to take effect; say which rather than leaving
  // the caller to discover it from a value that did not change.
  console.log(`${label}: note — shared_buffers-class settings need a restart; these do not.`);
  for (const k of Object.keys(map)) {
    console.log(`  ${k} = ${psqlValue(`SHOW ${k}`)}`);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// createdb
// ─────────────────────────────────────────────────────────────────────────────
function createTargetDb() {
  const exists = psqlValue(`SELECT 1 FROM pg_database WHERE datname = '${PG.database}'`);
  if (exists === '1') {
    console.log(`createdb: ${PG.database} already exists`);
  } else {
    // ICU en-US, matching the reasoning in lawmind.conf: the source is libc
    // en_US.utf8, which does not exist on Windows, and the schema names no
    // collation explicitly so nothing in the dump depends on the old name.
    run(exe('createdb'), [
      '--encoding=UTF8',
      '--locale-provider=icu',
      '--icu-locale=en-US',
      '--template=template0',
      PG.database,
    ]);
    console.log(`createdb: created ${PG.database}`);
  }

  // The three extensions the source carries, at the source's versions where the
  // local build allows it. pg_restore would create them itself from the dump,
  // but doing it here means a missing extension fails NOW — before a six-hour
  // restore — instead of as one skipped line inside it.
  for (const ext of ['pg_trgm', 'vector']) {
    try {
      psqlExec(`CREATE EXTENSION IF NOT EXISTS ${ext}`, PG.database);
      const v = psqlValue(`SELECT extversion FROM pg_extension WHERE extname='${ext}'`, PG.database);
      console.log(`createdb: extension ${ext} ${v}`);
    } catch (e) {
      console.error(`createdb: EXTENSION ${ext} FAILED — ${String(e.message).split('\n')[0]}`);
      console.error(`  This is a stop, not a warning. The source uses it and a restore without it`);
      console.error(`  produces a database that is missing columns, not one that is merely slower.`);
      process.exitCode = 1;
    }
  }
}

// ─────────────────────────────────────────────────────────────────────────────
function status() {
  console.log(`bin      ${PG.bin}`);
  console.log(`data     ${PG.data}`);
  console.log(`port     ${PG.port}`);
  console.log(`running  ${isRunning()}`);
  if (!isRunning()) return;
  console.log(`version  ${psqlValue('SHOW server_version')}`);
  for (const k of ['shared_buffers', 'work_mem', 'maintenance_work_mem', 'synchronous_commit', 'autovacuum', 'max_wal_size', 'listen_addresses']) {
    console.log(`  ${k.padEnd(22)} ${psqlValue(`SHOW ${k}`)}`);
  }
  const dbs = psqlValue(
    `SELECT string_agg(datname || ' (' || pg_size_pretty(pg_database_size(datname)) || ')', ', ' ORDER BY datname)
     FROM pg_database WHERE datistemplate = false`,
  );
  console.log(`  databases              ${dbs}`);
}

function main() {
  const [cmd, ...rest] = process.argv.slice(2);
  switch (cmd) {
    case 'configure':
      return configure();
    case 'start':
      return start();
    // Used by the LawMindPostgres scheduled task. Spawns and exits immediately:
    // the postmaster is detached, so the launcher's lifetime is irrelevant to
    // it, and a task that lingers waiting to report readiness is a task that can
    // be killed for lingering.
    case 'spawn-detached': {
      if (isRunning()) {
        console.log('spawn-detached: already running');
        return;
      }
      console.log(`spawn-detached: pid ${spawnPostmaster()}`);
      return;
    }
    case 'stop':
      return stop();
    case 'restart':
      stop();
      return start();
    case 'status':
      return status();
    case 'restore-mode':
      return applySettings(RESTORE_SETTINGS, 'restore-mode');
    case 'serve-mode':
      return applySettings(SERVE_SETTINGS, 'serve-mode');
    case 'createdb':
      return createTargetDb();
    case 'psql': {
      const r = run(exe('psql'), ['-d', PG.database, ...rest]);
      process.exit(r.status ?? 1);
      break;
    }
    default:
      console.log(
        'usage: pg-local.mjs configure|start|stop|restart|status|restore-mode|serve-mode|createdb|psql [args]',
      );
      process.exit(2);
  }
}

if (process.argv[1]?.endsWith('pg-local.mjs')) main();
