/**
 * LAWMIND — the screen inventory, as data.
 *
 * GENERATED from `design/screens/SCREENS.md`. Do not hand-edit — re-import the
 * design bundle and regenerate, or the inventory and the app drift apart.
 *
 * Every row has a canvas id and a render, or is marked NOT YET DESIGNED. There is
 * no third state and this file must keep it that way.
 *
 * THREE SURFACES:
 *   app    — screens on the phone, at `/s/<slug>` (four of them are tab routes)
 *   admin  — sections of the admin desk, a separate web app, at `/sections/<slug>`
 *   asset  — App Store material. Designed, but NOT a screen, so deliberately
 *            routeless. Giving a store screenshot an app route would be a dead
 *            route wearing a real one's clothes.
 *
 * One file, because `apps/admin` imports this manifest exactly as it imports
 * `tokens.ts` — no second copy of either.
 *
 * There is no catch-all route: a slug absent from this list is a 404, not a blank
 * shell.
 *
 * Sprint 0 builds SHELLS ONLY. Nothing here renders a citation — verified is
 * silent, and the two states that do render are built in S2 against the live data
 * model rather than guessed at now.
 */

export type ScreenSurface = 'app' | 'admin' | 'asset';

export type ScreenEntry = {
  /** Row number in `design/screens/SCREENS.md`. Stable; quote it in a bug report. */
  n: number;
  slug: string;
  title: string;
  group: string;
  surface: ScreenSurface;
  /** Null for a launch asset — App Store material is not a screen and has no route. */
  route: string | null;
  /** Option id inside the design canvas. Type `#8b` in the browser to jump to it. */
  canvas: string | null;
  /** Golden PNG under `design/screens/`. Renders 30+ are current; 00–29 are superseded v1/v2. */
  render: string | null;
  notes: string;
  /** False means NOT YET DESIGNED — the screen gets a stub that says so, never an improvised design. */
  designed: boolean;
};

export const SCREENS: readonly ScreenEntry[] = [
  {
    n: 1,
    slug: 'splash',
    title: 'Splash',
    group: 'Auth and onboarding',
    surface: 'app',
    route: '/s/splash',
    canvas: '10d',
    render: 'renders/44-splash-signin@2x.png',
    notes: 'Seal presses on an oxblood field; the icon opening up',
    designed: true,
  },
  {
    n: 2,
    slug: 'sign-in-enrolment-number',
    title: 'Sign-in — enrolment number',
    group: 'Auth and onboarding',
    surface: 'app',
    route: '/s/sign-in-enrolment-number',
    canvas: '10d',
    render: 'renders/44-splash-signin@2x.png',
    notes: 'Second frame. Enrolment number, not email',
    designed: true,
  },
  {
    n: 3,
    slug: 'magic-link-sent',
    title: 'Magic link sent',
    group: 'Auth and onboarding',
    surface: 'app',
    route: '/s/magic-link-sent',
    canvas: null,
    render: null,
    notes: 'NOT YET DESIGNED — auth method changed to enrolment number; confirm the verification channel before drawing',
    designed: false,
  },
  {
    n: 4,
    slug: 'onboarding-identity',
    title: 'Onboarding: identity',
    group: 'Auth and onboarding',
    surface: 'app',
    route: '/s/onboarding-identity',
    canvas: '2e',
    render: 'renders/10-onboarding.png',
    notes: 'v1 layout valid, colour and serif superseded',
    designed: true,
  },
  {
    n: 5,
    slug: 'onboarding-language',
    title: 'Onboarding: language',
    group: 'Auth and onboarding',
    surface: 'app',
    route: '/s/onboarding-language',
    canvas: '2e',
    render: 'renders/10-onboarding.png',
    notes: 'Same',
    designed: true,
  },
  {
    n: 6,
    slug: 'onboarding-first-matter',
    title: 'Onboarding: first matter',
    group: 'Auth and onboarding',
    surface: 'app',
    route: '/s/onboarding-first-matter',
    canvas: '10f',
    render: 'renders/48-first-run@2x.png',
    notes: 'Folded into first-run Matters',
    designed: true,
  },
  {
    n: 7,
    slug: 'today-briefing-ready',
    title: 'Today — briefing ready',
    group: 'Core — four tabs',
    surface: 'app',
    route: '/today',
    canvas: '6a 10b',
    render: 'renders/31-today@2x.png',
    notes: 'The primary screen. 10b shows it with the seal press live',
    designed: true,
  },
  {
    n: 8,
    slug: 'today-first-run-no-data',
    title: 'Today — first run, no data',
    group: 'Core — four tabs',
    surface: 'app',
    route: '/s/today-first-run-no-data',
    canvas: '10f',
    render: 'renders/48-first-run@2x.png',
    notes: 'Promise stated once, with the cost of acting on it',
    designed: true,
  },
  {
    n: 9,
    slug: 'today-no-hearings-this-week',
    title: 'Today — no hearings this week',
    group: 'Core — four tabs',
    surface: 'app',
    route: '/s/today-no-hearings-this-week',
    canvas: '1e',
    render: 'renders/11-states-offline-ai-down.png',
    notes: 'v1; derives one overdue obligation, no task model (§9.4)',
    designed: true,
  },
  {
    n: 10,
    slug: 'search-query-input',
    title: 'Search — query input',
    group: 'Core — four tabs',
    surface: 'app',
    route: '/search',
    canvas: '1i',
    render: 'renders/06-search-results.png',
    notes: 'v1 layout valid',
    designed: true,
  },
  {
    n: 11,
    slug: 'matters-list',
    title: 'Matters — list',
    group: 'Core — four tabs',
    surface: 'app',
    route: '/matters',
    canvas: '1t',
    render: 'renders/09-matter-detail.png',
    notes: 'v1 layout valid',
    designed: true,
  },
  {
    n: 12,
    slug: 'matters-first-run',
    title: 'Matters — first run',
    group: 'Core — four tabs',
    surface: 'app',
    route: '/s/matters-first-run',
    canvas: '10f',
    render: 'renders/48-first-run@2x.png',
    notes: 'Two routes, each with its real cost',
    designed: true,
  },
  {
    n: 13,
    slug: 'drafts-type-picker',
    title: 'Drafts — type picker',
    group: 'Core — four tabs',
    surface: 'app',
    route: '/drafts',
    canvas: '1o',
    render: null,
    notes: 'v1 layout valid; ten types grouped criminal/civil',
    designed: true,
  },
  {
    n: 14,
    slug: 'drafts-first-run',
    title: 'Drafts — first run',
    group: 'Core — four tabs',
    surface: 'app',
    route: '/s/drafts-first-run',
    canvas: '10f',
    render: 'renders/48-first-run@2x.png',
    notes: 'Leads with the most-filed type',
    designed: true,
  },
  {
    n: 15,
    slug: 'search-results-mixed-list',
    title: 'Search results — mixed list',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/search-results-mixed-list',
    canvas: '8a',
    render: 'renders/33-search-mixed-list@2x.png',
    notes: 'All five badge states in one list',
    designed: true,
  },
  {
    n: 16,
    slug: 'search-loading',
    title: 'Search — loading',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/search-loading',
    canvas: '5e 1l',
    render: 'renders/27-paper-search.png',
    notes: 'Shimmer, never a spinner',
    designed: true,
  },
  {
    n: 17,
    slug: 'search-no-results',
    title: 'Search — no results',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/search-no-results',
    canvas: '1l',
    render: null,
    notes: 'Explains *why*, offers the corrected query',
    designed: true,
  },
  {
    n: 18,
    slug: 'judgment-detail',
    title: 'Judgment detail',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/judgment-detail',
    canvas: '1m',
    render: 'renders/07-judgment-overruled.png',
    notes: 'v1 layout valid',
    designed: true,
  },
  {
    n: 19,
    slug: 'judgment-set-aside',
    title: 'Judgment — set_aside',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/judgment-set-aside',
    canvas: '3e',
    render: 'renders/19-overruled-three-states.png',
    notes: 'Danger band; add-to-matter disabled',
    designed: true,
  },
  {
    n: 20,
    slug: 'judgment-partly-set-aside',
    title: 'Judgment — partly_set_aside',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/judgment-partly-set-aside',
    canvas: '1n 3e',
    render: 'renders/19-overruled-three-states.png',
    notes: 'Caution band naming the paragraphs',
    designed: true,
  },
  {
    n: 21,
    slug: 'judgment-doubted',
    title: 'Judgment — doubted',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/judgment-doubted',
    canvas: '3e',
    render: 'renders/19-overruled-three-states.png',
    notes: 'No band; still binding',
    designed: true,
  },
  {
    n: 22,
    slug: 'unverified-citation-detail',
    title: 'Unverified citation detail',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/unverified-citation-detail',
    canvas: '10i',
    render: 'renders/49-unverified-citation@2x.png',
    notes: 'Four sources checked, each with a result and a timestamp; the eCourts path spelled out',
    designed: true,
  },
  {
    n: 23,
    slug: 'verification-badge-five-states',
    title: 'Verification badge — five states',
    group: 'Search and authority',
    surface: 'app',
    route: '/s/verification-badge-five-states',
    canvas: '7a 7d',
    render: 'renders/32-badge-family@3x.png, renders/43-badge-greyscale.png',
    notes: 'Build spec in IMPLEMENTATION.md §Badge',
    designed: true,
  },
  {
    n: 24,
    slug: 'matter-detail-timeline',
    title: 'Matter detail — timeline',
    group: 'Matters',
    surface: 'app',
    route: '/s/matter-detail-timeline',
    canvas: '1u',
    render: 'renders/09-matter-detail.png',
    notes: 'v1 layout valid',
    designed: true,
  },
  {
    n: 25,
    slug: 'add-matter-cnr-lookup',
    title: 'Add matter — CNR lookup',
    group: 'Matters',
    surface: 'app',
    route: '/s/add-matter-cnr-lookup',
    canvas: '1v',
    render: null,
    notes: 'v1 layout valid',
    designed: true,
  },
  {
    n: 26,
    slug: 'add-matter-manual',
    title: 'Add matter — manual',
    group: 'Matters',
    surface: 'app',
    route: '/s/add-matter-manual',
    canvas: '1v',
    render: null,
    notes: 'v1 layout valid',
    designed: true,
  },
  {
    n: 27,
    slug: 'add-event',
    title: 'Add event',
    group: 'Matters',
    surface: 'app',
    route: '/s/add-event',
    canvas: '1w',
    render: null,
    notes: 'v1 layout valid',
    designed: true,
  },
  {
    n: 28,
    slug: 'ocr-capture',
    title: 'OCR — capture',
    group: 'Matters',
    surface: 'app',
    route: '/s/ocr-capture',
    canvas: '10j',
    render: 'renders/50-ocr-flow@2x.png',
    notes: 'Edge detection confirms before the shutter; minors/witness warning before the photograph exists',
    designed: true,
  },
  {
    n: 29,
    slug: 'ocr-processing',
    title: 'OCR — processing',
    group: 'Matters',
    surface: 'app',
    route: '/s/ocr-processing',
    canvas: '10j',
    render: 'renders/50-ocr-flow@2x.png',
    notes: 'Field checklist resolves line by line; on-device stated twice',
    designed: true,
  },
  {
    n: 30,
    slug: 'ocr-field-confirmation',
    title: 'OCR — field confirmation',
    group: 'Matters',
    surface: 'app',
    route: '/s/ocr-field-confirmation',
    canvas: '10j',
    render: 'renders/50-ocr-flow@2x.png',
    notes: 'Per-field confidence; nothing saves until confirmed; photograph discarded after',
    designed: true,
  },
  {
    n: 31,
    slug: 'briefing-view',
    title: 'Briefing view',
    group: 'Briefing — the wedge',
    surface: 'app',
    route: '/s/briefing-view',
    canvas: '8b',
    render: 'renders/45-briefing@2x.png',
    notes: 'Paper masthead, oxblood rule, gilt seal ring, four blocks',
    designed: true,
  },
  {
    n: 32,
    slug: 'briefing-notification',
    title: 'Briefing notification',
    group: 'Briefing — the wedge',
    surface: 'app',
    route: '/s/briefing-notification',
    canvas: '10b',
    render: 'renders/46-seal-moment@2x.png',
    notes: 'Seal presses inside the lock-screen notification',
    designed: true,
  },
  {
    n: 33,
    slug: 'the-seal-press',
    title: 'The seal press',
    group: 'Briefing — the wedge',
    surface: 'app',
    route: '/s/the-seal-press',
    canvas: '10a',
    render: 'renders/46-seal-moment@2x.png',
    notes: 'Frame-by-frame, 620ms, one ritual haptic at 0.42',
    designed: true,
  },
  {
    n: 34,
    slug: 'briefing-offline',
    title: 'Briefing — offline',
    group: 'Briefing — the wedge',
    surface: 'app',
    route: '/s/briefing-offline',
    canvas: '9b',
    render: 'renders/37-honest-states@2x.png',
    notes: 'Saved card keeps its seal; staleness stated',
    designed: true,
  },
  {
    n: 35,
    slug: 'draft-input-form',
    title: 'Draft input form',
    group: 'Drafting',
    surface: 'app',
    route: '/s/draft-input-form',
    canvas: '1p',
    render: null,
    notes: 'v1 layout valid; six fields, four matter-prefilled',
    designed: true,
  },
  {
    n: 36,
    slug: 'draft-output',
    title: 'Draft output',
    group: 'Drafting',
    surface: 'app',
    route: '/s/draft-output',
    canvas: '8c',
    render: 'renders/47-draft-output@2x.png',
    notes: 'AI-mark header band; inline registry stamps',
    designed: true,
  },
  {
    n: 37,
    slug: 'draft-output-hindi',
    title: 'Draft output — Hindi',
    group: 'Drafting',
    surface: 'app',
    route: '/s/draft-output-hindi',
    canvas: '9a',
    render: 'renders/36-hindi-parity@2x.png',
    notes: 'Devanagari body, citations stay English',
    designed: true,
  },
  {
    n: 38,
    slug: 'ai-mark-removal',
    title: 'AI-mark removal',
    group: 'Drafting',
    surface: 'app',
    route: '/s/ai-mark-removal',
    canvas: '10b',
    render: 'renders/46-seal-moment@2x.png',
    notes: 'The quieter sibling: ink, no glint, second person',
    designed: true,
  },
  {
    n: 39,
    slug: 'profile',
    title: 'Profile',
    group: 'Account',
    surface: 'app',
    route: '/s/profile',
    canvas: '1y',
    render: null,
    notes: 'v1 layout valid',
    designed: true,
  },
  {
    n: 40,
    slug: 'subscription',
    title: 'Subscription',
    group: 'Account',
    surface: 'app',
    route: '/s/subscription',
    canvas: '10k',
    render: 'renders/51-subscription@2x.png',
    notes: 'Four tiers, no buy button, managed on the web',
    designed: true,
  },
  {
    n: 41,
    slug: 'settings',
    title: 'Settings',
    group: 'Account',
    surface: 'app',
    route: '/s/settings',
    canvas: '1y',
    render: 'renders/20-settings-switches.png',
    notes: 'Switch spec in IMPLEMENTATION.md §Switch',
    designed: true,
  },
  {
    n: 42,
    slug: 'privacy-disclosure',
    title: 'Privacy disclosure',
    group: 'Account',
    surface: 'app',
    route: '/s/privacy-disclosure',
    canvas: '9b',
    render: 'renders/37-honest-states@2x.png',
    notes: 'States plainly what it cannot promise',
    designed: true,
  },
  {
    n: 43,
    slug: 'offline',
    title: 'Offline',
    group: 'System states',
    surface: 'app',
    route: '/s/offline',
    canvas: '9b',
    render: 'renders/37-honest-states@2x.png',
    notes: 'What is readable, what is not, and when it was saved',
    designed: true,
  },
  {
    n: 44,
    slug: 'ai-unavailable',
    title: 'AI unavailable',
    group: 'System states',
    surface: 'app',
    route: '/s/ai-unavailable',
    canvas: '9b',
    render: 'renders/37-honest-states@2x.png',
    notes: 'Refuses to answer from cache; three real alternatives',
    designed: true,
  },
  {
    n: 45,
    slug: 'empty-no-matters',
    title: 'Empty — no matters',
    group: 'System states',
    surface: 'app',
    route: '/s/empty-no-matters',
    canvas: '9b 10f',
    render: 'renders/48-first-run@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 46,
    slug: 'sunlight-stress-test',
    title: 'Sunlight stress test',
    group: 'System states',
    surface: 'app',
    route: '/s/sunlight-stress-test',
    canvas: '9c',
    render: 'renders/38-stress-sunlight@2x.png',
    notes: 'Design gate, not a checkbox',
    designed: true,
  },
  {
    n: 47,
    slug: 'messy-data-stress-test',
    title: 'Messy-data stress test',
    group: 'System states',
    surface: 'app',
    route: '/s/messy-data-stress-test',
    canvas: '9c',
    render: 'renders/38-stress-sunlight@2x.png',
    notes: 'Six reporter citations, 96-char case title',
    designed: true,
  },
  {
    n: 48,
    slug: 'design-system-sheet',
    title: 'Design system sheet',
    group: 'Identity and system reference',
    surface: 'app',
    route: '/s/design-system-sheet',
    canvas: '6c',
    render: 'renders/30-system-refined@2x.png',
    notes: 'Palette, type scale, rules, buttons, inputs, card anatomy',
    designed: true,
  },
  {
    n: 49,
    slug: 'app-icon',
    title: 'App icon',
    group: 'Identity and system reference',
    surface: 'app',
    route: '/s/app-icon',
    canvas: '10c',
    render: 'renders/52-app-icon@2x.png',
    notes: 'Four sizes, light and dark home screens',
    designed: true,
  },
  {
    n: 50,
    slug: 'logo-animated-and-static',
    title: 'Logo — animated and static',
    group: 'Identity and system reference',
    surface: 'app',
    route: '/s/logo-animated-and-static',
    canvas: '3a',
    render: 'renders/00-logo-real-mark.png',
    notes: 'The supplied gavel Lottie; static renders frame 34 of the same file',
    designed: true,
  },
  {
    n: 51,
    slug: 'micro-typography',
    title: 'Micro-typography',
    group: 'Identity and system reference',
    surface: 'app',
    route: '/s/micro-typography',
    canvas: '10e',
    render: 'renders/53-micro-typography@2x.png',
    notes: 'Before/after, same content',
    designed: true,
  },
  {
    n: 52,
    slug: 'glass-on-chrome',
    title: 'Glass on chrome',
    group: 'Identity and system reference',
    surface: 'app',
    route: '/s/glass-on-chrome',
    canvas: '10g',
    render: 'renders/54-glass-chrome@2x.png',
    notes: 'Tab bar, sheet, toast, reduced brightness',
    designed: true,
  },
  {
    n: 53,
    slug: 'gilt-two-placements',
    title: 'Gilt — two placements',
    group: 'Identity and system reference',
    surface: 'app',
    route: '/s/gilt-two-placements',
    canvas: '10h',
    render: 'renders/55-gilt-two-placements@2x.png',
    notes: 'Ornament, carries nothing',
    designed: true,
  },
  {
    n: 54,
    slug: 'motion-and-haptics',
    title: 'Motion and haptics',
    group: 'Identity and system reference',
    surface: 'app',
    route: '/s/motion-and-haptics',
    canvas: '5b',
    render: 'renders/24-motion-system.png',
    notes: 'Springs, stagger, haptic map',
    designed: true,
  },
  {
    n: 55,
    slug: 'overview',
    title: 'Overview',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/overview',
    canvas: null,
    render: 'renders/13-admin-overview.png',
    notes: '',
    designed: true,
  },
  {
    n: 56,
    slug: 'enrolment-queue',
    title: 'Enrolment queue',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/enrolment-queue',
    canvas: null,
    render: 'renders/16-admin-enrolment-queue.png',
    notes: '',
    designed: true,
  },
  {
    n: 57,
    slug: 'advocates',
    title: 'Advocates',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/advocates',
    canvas: null,
    render: null,
    notes: 'In the live file',
    designed: true,
  },
  {
    n: 58,
    slug: 'briefings',
    title: 'Briefings',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/briefings',
    canvas: null,
    render: 'renders/15-admin-platform-controls.png',
    notes: 'Composition blocks',
    designed: true,
  },
  {
    n: 59,
    slug: 'cause-list-sync',
    title: 'Cause list sync',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/cause-list-sync',
    canvas: null,
    render: 'renders/39-admin-causelist.png',
    notes: 'The failure mode that silently poisons briefings',
    designed: true,
  },
  {
    n: 60,
    slug: 'citation-monitor',
    title: 'Citation monitor',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/citation-monitor',
    canvas: null,
    render: 'renders/17-admin-citation-monitor.png',
    notes: '',
    designed: true,
  },
  {
    n: 61,
    slug: 'disputed-citations',
    title: 'Disputed citations',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/disputed-citations',
    canvas: null,
    render: 'renders/40-admin-disputes.png',
    notes: 'Outranks everything else in the admin',
    designed: true,
  },
  {
    n: 62,
    slug: 'ocr-review-queue',
    title: 'OCR review queue',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/ocr-review-queue',
    canvas: null,
    render: 'renders/56-admin-ocr-queue@2x.png',
    notes: 'Correction pairs only — we never see the photograph',
    designed: true,
  },
  {
    n: 63,
    slug: 'corpus-ingestion',
    title: 'Corpus & ingestion',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/corpus-ingestion',
    canvas: null,
    render: null,
    notes: 'In the live file',
    designed: true,
  },
  {
    n: 64,
    slug: 'draft-templates',
    title: 'Draft templates',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/draft-templates',
    canvas: null,
    render: 'renders/41-admin-templates.png',
    notes: 'Versioned prompts, golden-set scores',
    designed: true,
  },
  {
    n: 65,
    slug: 'llm-spend-routing',
    title: 'LLM spend & routing',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/llm-spend-routing',
    canvas: null,
    render: 'renders/57-admin-routing@2x.png',
    notes: 'Keyed by data class, with the blocked state',
    designed: true,
  },
  {
    n: 66,
    slug: 'subscriptions',
    title: 'Subscriptions',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/subscriptions',
    canvas: null,
    render: 'renders/21-admin-subscriptions.png',
    notes: '',
    designed: true,
  },
  {
    n: 67,
    slug: 'support-inbox',
    title: 'Support inbox',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/support-inbox',
    canvas: null,
    render: null,
    notes: 'In the live file',
    designed: true,
  },
  {
    n: 68,
    slug: 'push-campaigns',
    title: 'Push campaigns',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/push-campaigns',
    canvas: null,
    render: null,
    notes: 'In the live file',
    designed: true,
  },
  {
    n: 69,
    slug: 'platform-controls',
    title: 'Platform controls',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/platform-controls',
    canvas: null,
    render: 'renders/15-admin-platform-controls.png',
    notes: 'Kill switches',
    designed: true,
  },
  {
    n: 70,
    slug: 'data-deletion',
    title: 'Data & deletion',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/data-deletion',
    canvas: null,
    render: 'renders/42-admin-privacy.png',
    notes: 'DPDP clocks, retention, pseudonymisation coverage',
    designed: true,
  },
  {
    n: 71,
    slug: 'staff-audit',
    title: 'Staff & audit',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/staff-audit',
    canvas: null,
    render: null,
    notes: 'In the live file',
    designed: true,
  },
  {
    n: 72,
    slug: 'analytics',
    title: 'Analytics',
    group: 'Admin — seventeen sections',
    surface: 'admin',
    route: '/sections/analytics',
    canvas: null,
    render: null,
    notes: 'In the live file',
    designed: true,
  },
  {
    n: 73,
    slug: 'sign-in-otp',
    title: 'Sign-in — OTP',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/sign-in-otp',
    canvas: '11a',
    render: 'renders/58-signin-otp@2x.png',
    notes: 'SMS OTP to any number; enrolment verified separately',
    designed: true,
  },
  {
    n: 74,
    slug: 'enrolment-pending',
    title: 'Enrolment pending',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/enrolment-pending',
    canvas: '11a',
    render: 'renders/58-signin-otp@2x.png',
    notes: 'Full access, quiet amber band',
    designed: true,
  },
  {
    n: 75,
    slug: 'matter-sharing',
    title: 'Matter sharing',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/matter-sharing',
    canvas: '11b',
    render: 'renders/59-chamber-sharing@2x.png',
    notes: 'Per matter, by invitation, names not roles',
    designed: true,
  },
  {
    n: 76,
    slug: 'notes-private-and-shared',
    title: 'Notes — private and shared',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/notes-private-and-shared',
    canvas: '11b',
    render: 'renders/59-chamber-sharing@2x.png',
    notes: 'Private by default, shareable per note',
    designed: true,
  },
  {
    n: 77,
    slug: 'shared-briefing-junior-view',
    title: 'Shared briefing — junior view',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/shared-briefing-junior-view',
    canvas: '11b',
    render: 'renders/59-chamber-sharing@2x.png',
    notes: 'Names whose matter it is; instruction above the record',
    designed: true,
  },
  {
    n: 78,
    slug: 'citator-alerts-in-the-briefing',
    title: 'Citator alerts — in the briefing',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/citator-alerts-in-the-briefing',
    canvas: '11c',
    render: 'renders/60-citator-alerts@2x.png',
    notes: 'Batched nightly, four triggers',
    designed: true,
  },
  {
    n: 79,
    slug: 'citator-alert-the-one-push',
    title: 'Citator alert — the one push',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/citator-alert-the-one-push',
    canvas: '11c',
    render: 'renders/60-citator-alerts@2x.png',
    notes: 'Only when it affects tomorrow. Danger tint, never gilt',
    designed: true,
  },
  {
    n: 80,
    slug: 'alert-settings',
    title: 'Alert settings',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/alert-settings',
    canvas: '11c',
    render: 'renders/60-citator-alerts@2x.png',
    notes: 'Filed-draft trigger cannot be disabled',
    designed: true,
  },
  {
    n: 81,
    slug: 'draft-paragraph-editing',
    title: 'Draft — paragraph editing',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/draft-paragraph-editing',
    canvas: '11d',
    render: 'renders/61-draft-editing@2x.png',
    notes: 'Citations locked; neighbours at 34%',
    designed: true,
  },
  {
    n: 82,
    slug: 'draft-export-sheet',
    title: 'Draft — export sheet',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/draft-export-sheet',
    canvas: '11d',
    render: 'renders/61-draft-editing@2x.png',
    notes: '.docx default; the mark travels',
    designed: true,
  },
  {
    n: 83,
    slug: 'judgment-reading-view',
    title: 'Judgment — reading view',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/judgment-reading-view',
    canvas: '11e',
    render: 'renders/62-judgment-reading@2x.png',
    notes: 'Anchors, highlight, save to matter',
    designed: true,
  },
  {
    n: 84,
    slug: 'judgment-reading-sheet',
    title: 'Judgment — reading sheet',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/judgment-reading-sheet',
    canvas: '11e',
    render: 'renders/62-judgment-reading@2x.png',
    notes: 'Size as words-per-screen, structure, progress',
    designed: true,
  },
  {
    n: 85,
    slug: 'judgment-in-text-search',
    title: 'Judgment — in-text search',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/judgment-in-text-search',
    canvas: '11e',
    render: 'renders/62-judgment-reading@2x.png',
    notes: 'Jumps between paragraphs, not scroll positions',
    designed: true,
  },
  {
    n: 86,
    slug: 'search-filters-expanded',
    title: 'Search filters — expanded',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/search-filters-expanded',
    canvas: '11f',
    render: 'renders/63-search-filters@2x.png',
    notes: 'Five sections; judge and reporter dropped',
    designed: true,
  },
  {
    n: 87,
    slug: 'filtered-results',
    title: 'Filtered results',
    group: 'The seven, now drawn',
    surface: 'app',
    route: '/s/filtered-results',
    canvas: '11f',
    render: 'renders/63-search-filters@2x.png',
    notes: 'Hidden results are named, never silent',
    designed: true,
  },
  {
    n: 88,
    slug: 'search-results-before-and-after',
    title: 'Search results — before and after',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/search-results-before-and-after',
    canvas: '12a',
    render: 'renders/64-verified-silent@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 89,
    slug: 'judgment-detail-no-badge',
    title: 'Judgment detail — no badge',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/judgment-detail-no-badge',
    canvas: '12b',
    render: 'renders/65-judgment-quiet@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 90,
    slug: 'verification-on-tap',
    title: 'Verification on tap',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/verification-on-tap',
    canvas: '12b',
    render: 'renders/65-judgment-quiet@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 91,
    slug: 'briefing-authorities-quiet',
    title: 'Briefing authorities — quiet',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/briefing-authorities-quiet',
    canvas: '12b',
    render: 'renders/65-judgment-quiet@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 92,
    slug: 'consent-screen',
    title: 'Consent screen',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/consent-screen',
    canvas: '12c',
    render: 'renders/66-consent-clean-draft@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 93,
    slug: 'draft-output-no-mark',
    title: 'Draft output — no mark',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/draft-output-no-mark',
    canvas: '12c',
    render: 'renders/66-consent-clean-draft@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 94,
    slug: 'draft-footer-risk-state',
    title: 'Draft footer — risk state',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/draft-footer-risk-state',
    canvas: '12c',
    render: 'renders/66-consent-clean-draft@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 95,
    slug: 'privacy-at-onboarding',
    title: 'Privacy at onboarding',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/privacy-at-onboarding',
    canvas: '12d',
    render: 'renders/67-privacy-ocr-quiet@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 96,
    slug: 'ocr-normal-review-step',
    title: 'OCR — normal review step',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Verification inverted — verified renders nothing',
    surface: 'app',
    route: '/s/ocr-normal-review-step',
    canvas: '12d',
    render: 'renders/67-privacy-ocr-quiet@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 97,
    slug: 'daily-cause-list',
    title: 'Daily cause list',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/daily-cause-list',
    canvas: '12e',
    render: 'renders/68-cause-list@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 98,
    slug: 'cause-list-outcome-sheet',
    title: 'Cause list — outcome sheet',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/cause-list-outcome-sheet',
    canvas: '12e',
    render: 'renders/68-cause-list@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 99,
    slug: 'adjournment-capture',
    title: 'Adjournment capture',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/adjournment-capture',
    canvas: '12f',
    render: 'renders/69-adjournment@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 100,
    slug: 'adjournment-confirmation',
    title: 'Adjournment — confirmation',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/adjournment-confirmation',
    canvas: '12f',
    render: 'renders/69-adjournment@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 101,
    slug: 'client-update-compose',
    title: 'Client update — compose',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/client-update-compose',
    canvas: '12g',
    render: 'renders/70-client-share@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 102,
    slug: 'the-shared-card-in-whatsapp',
    title: 'The shared card in WhatsApp',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/the-shared-card-in-whatsapp',
    canvas: '12g',
    render: 'renders/70-client-share@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 103,
    slug: 'limitation-calculator',
    title: 'Limitation calculator',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/limitation-calculator',
    canvas: '12h',
    render: 'renders/71-limitation@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 104,
    slug: 'limitation-barred',
    title: 'Limitation — barred',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/limitation-barred',
    canvas: '12h',
    render: 'renders/71-limitation@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 105,
    slug: 'bare-acts-index',
    title: 'Bare acts — index',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/bare-acts-index',
    canvas: '12i',
    render: 'renders/72-bare-acts@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 106,
    slug: 'bare-acts-reading-bns',
    title: 'Bare acts — reading BNS',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/bare-acts-reading-bns',
    canvas: '12i',
    render: 'renders/72-bare-acts@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 107,
    slug: 'ipc-bns-comparison',
    title: 'IPC ↔ BNS comparison',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/ipc-bns-comparison',
    canvas: '12i',
    render: 'renders/72-bare-acts@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 108,
    slug: 'fee-and-appearance-log',
    title: 'Fee and appearance log',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/fee-and-appearance-log',
    canvas: '12j',
    render: 'renders/73-fee-log@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 109,
    slug: 'fee-log-add-entry',
    title: 'Fee log — add entry',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — The daily loop',
    surface: 'app',
    route: '/s/fee-log-add-entry',
    canvas: '12j',
    render: 'renders/73-fee-log@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 110,
    slug: 'eight-store-screenshots-captions',
    title: 'Eight store screenshots + captions',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Launch assets',
    surface: 'asset',
    route: null,
    canvas: '12k',
    render: 'renders/74-store-screenshots@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 111,
    slug: 'icon-in-a-real-search-result',
    title: 'Icon in a real search result',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Launch assets',
    surface: 'asset',
    route: null,
    canvas: '12l',
    render: 'renders/75-store-listing@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 112,
    slug: 'subtitle-feature-graphic-description',
    title: 'Subtitle, feature graphic, description',
    group: 'Turn 12 — the silence pass, the daily loop, launch assets — Launch assets',
    surface: 'asset',
    route: null,
    canvas: '12l',
    render: 'renders/75-store-listing@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 113,
    slug: 'search-results-silence-rule-applied',
    title: 'Search results — silence rule applied',
    group: 'Turn 13 — silence corrections, pricing, the last library screens',
    surface: 'app',
    route: '/s/search-results-silence-rule-applied',
    canvas: '13a',
    render: 'renders/33-search-mixed-list@2x.png (replacement)',
    notes: '',
    designed: true,
  },
  {
    n: 114,
    slug: 'briefing-authorities-silence-rule-applied',
    title: 'Briefing authorities — silence rule applied',
    group: 'Turn 13 — silence corrections, pricing, the last library screens',
    surface: 'app',
    route: '/s/briefing-authorities-silence-rule-applied',
    canvas: '13a',
    render: 'renders/34-briefing@2x.png (replacement)',
    notes: '',
    designed: true,
  },
  {
    n: 115,
    slug: 'paywall-practice-chamber-expert-firm',
    title: 'Paywall — Practice · Chamber · Expert · Firm',
    group: 'Turn 13 — silence corrections, pricing, the last library screens',
    surface: 'app',
    route: '/s/paywall-practice-chamber-expert-firm',
    canvas: '13b',
    render: 'renders/76-pricing@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 116,
    slug: 'founding-offer',
    title: 'Founding offer',
    group: 'Turn 13 — silence corrections, pricing, the last library screens',
    surface: 'app',
    route: '/s/founding-offer',
    canvas: '13b',
    render: 'renders/76-pricing@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 117,
    slug: 'legal-dictionary',
    title: 'Legal dictionary',
    group: 'Turn 13 — silence corrections, pricing, the last library screens',
    surface: 'app',
    route: '/s/legal-dictionary',
    canvas: '13c',
    render: 'renders/77-library-three@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 118,
    slug: 'court-rules-reader',
    title: 'Court rules reader',
    group: 'Turn 13 — silence corrections, pricing, the last library screens',
    surface: 'app',
    route: '/s/court-rules-reader',
    canvas: '13c',
    render: 'renders/77-library-three@2x.png',
    notes: '',
    designed: true,
  },
  {
    n: 119,
    slug: 'court-fee-calculator',
    title: 'Court fee calculator',
    group: 'Turn 13 — silence corrections, pricing, the last library screens',
    surface: 'app',
    route: '/s/court-fee-calculator',
    canvas: '13c',
    render: 'renders/77-library-three@2x.png',
    notes: '',
    designed: true,
  },
];

/** A screen that actually has a route. Only `asset` rows do not. */
export type RoutedScreen = ScreenEntry & { route: string };

const routed = (surface: ScreenSurface) =>
  SCREENS.filter((s): s is RoutedScreen => s.surface === surface && s.route !== null);

export const APP_SCREENS = routed('app');
export const ADMIN_SCREENS = routed('admin');
export const screenByNumber = (n: number): ScreenEntry | undefined =>
  SCREENS.find((s) => s.n === n);

/** Section order as it appears in the inventory. */
export const screenGroups = (surface: ScreenSurface): string[] =>
  Array.from(new Set(SCREENS.filter((s) => s.surface === surface).map((s) => s.group)));
