/**
 * ─────────────────────────────────────────────────────────────────────────────
 * TENANT ISOLATION — A LEGAL_SECURITY RELEASE GATE, NOT A UNIT TEST
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * `/admin/*` is deny-by-default since migration `0074`, and 31 admin tests pass.
 * **That proves nothing about tenant isolation.** Admin authorisation asks "is
 * this caller an administrator"; tenant isolation asks "is this ROW this
 * caller's", and the two are enforced in completely different places — the first
 * in one middleware, the second in the WHERE clause of every handler that
 * touches a user-owned table. A missed `AND user_id = ...` in any one of them is
 * an IDOR, and no amount of admin testing can see it.
 *
 * What a defect here costs is specific to this product. A matter row carries the
 * client's name, the party detail, and notes an advocate wrote about their own
 * client's case. Two advocates on opposite sides of the same litigation are both
 * LawMind users. An IDOR is not "a data leak" here; it is privileged material
 * crossing between opposing counsel.
 *
 * ─────────────────────────────────────────────────────────────────────────────
 * WHAT IT ASSERTS, AND THE ONE THING IT DELIBERATELY DOES NOT
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * USER_A creates every private object the API can create. USER_B then attempts
 * READ, WRITE and DELETE on each of them **by direct id**, with a valid token of
 * their own — the exact shape of a real attack, which is not an unauthenticated
 * request but an authenticated one pointed at somebody else's row.
 *
 * The expected answer is 404, not 403, and that is a deliberate product rule
 * rather than laziness: **"not found" and "not yours" must be indistinguishable**
 * (`matters/route.test.ts` §1). A 403 on a matter id confirms that the id exists,
 * which is itself a fact about another advocate's caseload — an oracle an
 * attacker can walk. So the assertion accepts 404 and REFUSES 200, and records a
 * 403 on a user-owned row as `PASS_BUT_ORACLE` rather than silently as a pass.
 *
 * It does NOT assert that a listing endpoint returns zero rows for USER_B —
 * USER_B has their own rows and should see them. What it asserts is that USER_A's
 * ids never appear in USER_B's list, which is the property that actually matters
 * and the one a count cannot check.
 *
 * Every object is seeded through the REAL routes wherever a route exists, so a
 * handler that writes `user_id` from the wrong place is caught. Where no create
 * route exists (briefings are generated by the nightly sweep, documents by the
 * drafting job) the row is inserted directly and the READ path is what is tested.
 */
import assert from 'node:assert/strict';
import { after, before, describe, it } from 'node:test';

import { signAccessToken } from '@lawmind/auth';
import postgres from 'postgres';

import { createApp } from '../app.ts';

const sql = postgres(process.env['DATABASE_URL'] ?? '', { max: 4, onnotice: () => {} });
const SECRET = 'test-secret-not-used-anywhere-real-0123456789';
const TAG = 'test-tenant-';

const app = createApp({
  ping: async () => {},
  search: { sql, embedQuery: async () => null },
  auth: { auth: null as never, sql, secret: SECRET },
});

type Actor = { authId: string; userId: string; token: string; email: string };

async function seed(tag: string, role: 'advocate' | 'admin' = 'advocate'): Promise<Actor> {
  const authId = `${TAG}${tag}-${crypto.randomUUID()}`;
  const email = `${authId}@example.test`;
  await sql`INSERT INTO auth_user (id, name, email, email_verified)
            VALUES (${authId}, 'Adv', ${email}, true)`;
  const [u] = await sql<{ id: string }[]>`
    INSERT INTO users (auth_id, full_name, phone, email, enrolment_status, role)
    VALUES (${authId}, 'Adv', '+911111111111', ${email}, 'unverified', ${role})
    RETURNING id`;
  return {
    authId,
    userId: u!.id,
    email,
    token: await signAccessToken({ sub: authId, email }, SECRET),
  };
}

const hdr = (t: string) => ({ authorization: `Bearer ${t}`, 'content-type': 'application/json' });

/**
 * The id out of a create response, whatever the route calls it.
 *
 * Deliberately tolerant rather than hard-coded per route: these handlers name
 * their key after the resource (`matterId`, `eventId`, `annotationId`), and a
 * battery that hard-codes one of them fails as a MISSING TEST the moment a route
 * renames its key — which is the worst possible failure mode for a security gate,
 * because it looks like a pass.
 */
function idFrom(payload: unknown, key: string): string {
  const data = (payload as { data?: Record<string, unknown> } | undefined)?.data ?? {};
  const nested = (data[key] ?? data) as Record<string, unknown>;
  for (const k of Object.keys(nested)) {
    if (k === 'id' || (k.endsWith('Id') && typeof nested[k] === 'string')) return nested[k] as string;
  }
  throw new Error(`no id found in create response for ${key}: ${JSON.stringify(payload).slice(0, 200)}`);
}

/**
 * One row of the reported matrix. A 403 passes the security question and is
 * still recorded separately, because the product rule is 404 and a drift from it
 * hands an attacker an existence oracle.
 */
type Finding = {
  resource: string;
  op: 'READ' | 'WRITE' | 'DELETE' | 'LIST';
  status: number;
  result: 'PASS' | 'FAIL' | 'PASS_BUT_ORACLE' | 'INCONCLUSIVE';
};
const matrix: Finding[] = [];

function record(resource: string, op: Finding['op'], status: number, expect403 = false): Finding {
  /**
   * `/admin/*` is the one surface where 403 is the RIGHT answer rather than a
   * tolerated one. Nothing about an admin path is a per-row identity, so
   * refusing by role discloses nothing an attacker can walk — the 404-not-403
   * rule exists to stop an id being confirmed, and there is no id here.
   */
  if (expect403) {
    const f: Finding = {
      resource,
      op,
      status,
      result: status === 403 || status === 401 ? 'PASS' : 'FAIL',
    };
    matrix.push(f);
    return f;
  }
  /**
   * 400 is INCONCLUSIVE, never a pass.
   *
   * A request rejected by the body validator never reached the ownership check,
   * so it proves nothing about isolation — and it is exactly how a security
   * battery rots into decoration: someone tightens a schema, every cross-tenant
   * probe starts bouncing at 400, and the suite stays green while testing
   * nothing. Recorded as its own state so it shows up in the matrix and in the
   * assertion, rather than being counted either way.
   */
  const result: Finding['result'] =
    status === 404 || status === 401
      ? 'PASS'
      : status === 403
        ? 'PASS_BUT_ORACLE'
        : status === 400
          ? 'INCONCLUSIVE'
          : 'FAIL';
  const f = { resource, op, status, result };
  matrix.push(f);
  return f;
}

/**
 * The assertion every cross-tenant attempt makes. A 2xx is the failure — and so
 * is an INCONCLUSIVE 400, because a probe that never reached the ownership check
 * has not tested it.
 */
function refused(resource: string, op: Finding['op'], status: number) {
  const f = record(resource, op, status);
  assert.notEqual(
    f.result,
    'FAIL',
    `IDOR: ${op} ${resource} by a foreign user returned ${status} — expected 404`,
  );
  assert.notEqual(
    f.result,
    'INCONCLUSIVE',
    `${op} ${resource} bounced at the body validator (400) and never reached the ` +
      `ownership check — fix the probe body, do not accept this as a pass`,
  );
}

describe('tenant isolation — USER_A, USER_B, ADMIN', () => {
  let A: Actor;
  let B: Actor;
  let ADMIN: Actor;

  /** A-owned ids, filled by `before`. */
  const owned: Record<string, string> = {};

  before(async () => {
    A = await seed('a');
    B = await seed('b');
    ADMIN = await seed('admin', 'admin');

    // ── matter, through the real route ──────────────────────────────────────
    const m = await app.request('/matters', {
      method: 'POST',
      headers: hdr(A.token),
      body: JSON.stringify({
        caseTitle: 'A v. Confidential',
        court: 'Delhi High Court',
        caseType: 'criminal',
        parties: { petitioner: 'A', respondent: 'Confidential' },
        clientName: 'A privileged client name',
        ourSide: 'accused',
        nextHearingDate: '2026-09-01',
      }),
    });
    assert.equal(m.status, 201);
    owned['matter'] = idFrom(await m.json(), 'matter');

    // ── matter event ────────────────────────────────────────────────────────
    const ev = await app.request(`/matters/${owned['matter']}/events`, {
      method: 'POST',
      headers: hdr(A.token),
      body: JSON.stringify({
        eventType: 'note',
        eventDate: '2026-08-20',
        description: 'privileged note',
      }),
    });
    if (ev.status === 201) owned['event'] = idFrom(await ev.json(), 'event');

    // ── saved search ────────────────────────────────────────────────────────
    const ss = await app.request('/saved-searches', {
      method: 'POST',
      headers: hdr(A.token),
      body: JSON.stringify({ query: 'anticipatory bail twin conditions', language: 'en' }),
    });
    assert.ok(
      ss.status === 200 || ss.status === 201,
      `could not seed a saved search (${ss.status})`,
    );
    owned['savedSearch'] = idFrom(await ss.json(), 'savedSearch');

    // ── annotation, on a real (public) judgment ─────────────────────────────
    const [j] = await sql<{ id: string }[]>`SELECT id FROM judgments LIMIT 1`;
    if (j) {
      owned['judgment'] = j.id;
      const an = await app.request(`/judgments/${j.id}/annotations`, {
        method: 'POST',
        headers: hdr(A.token),
        body: JSON.stringify({
          paragraphNumber: 1,
          paragraphIndex: 0,
          quote: 'a quoted passage',
          note: 'privileged annotation',
        }),
      });
      assert.ok(
        an.status === 200 || an.status === 201,
        `could not seed an annotation (${an.status}) — a battery that SKIPS is the ` +
          `failure mode this file exists to prevent`,
      );
      owned['annotation'] = idFrom(await an.json(), 'annotation');
    }

    // ── matter authority — the add-to-matter surface ────────────────────────
    if (owned['judgment']) {
      const auth = await app.request(`/matters/${owned['matter']}/authorities`, {
        method: 'POST',
        headers: hdr(A.token),
        body: JSON.stringify({ judgmentId: owned['judgment'] }),
      });
      // 409 is legitimate (`set_aside` disables add-to-matter, PD/OD-14); only a
      // 201 gives us an id to attack, and the absence is recorded rather than
      // silently skipped.
      if (auth.status === 201) owned['authority'] = idFrom(await auth.json(), 'authority');
    }

    // ── document — no create route in S1; the READ/WRITE paths are the test ──
    const [doc] = await sql<{ id: string }[]>`
      INSERT INTO documents (user_id, document_type, input_params, generated_content, language)
      VALUES (${A.userId}, 'legal_notice', '{}'::jsonb, 'privileged draft body', 'en')
      RETURNING id`;
    owned['document'] = doc!.id;

    // ── briefing — generated by the nightly sweep, read by the advocate ──────
    const [br] = await sql<{ id: string }[]>`
      INSERT INTO briefings (matter_id, hearing_date, generated_at, content, hearing_date_source)
      VALUES (${owned['matter']!}, '2026-09-01', now(),
              ${JSON.stringify({ blocks: [{ kind: 'note', text: 'privileged briefing' }] })}::jsonb,
              'advocate')
      RETURNING id`;
    owned['briefing'] = br!.id;
  });

  after(async () => {
    const like = `${TAG}%`;
    await sql`DELETE FROM briefings WHERE matter_id IN
              (SELECT m.id FROM matters m JOIN users u ON u.id = m.user_id WHERE u.auth_id LIKE ${like})`;
    await sql`DELETE FROM matter_events WHERE matter_id IN
              (SELECT m.id FROM matters m JOIN users u ON u.id = m.user_id WHERE u.auth_id LIKE ${like})`;
    await sql`DELETE FROM matter_authorities WHERE matter_id IN
              (SELECT m.id FROM matters m JOIN users u ON u.id = m.user_id WHERE u.auth_id LIKE ${like})`;
    await sql`DELETE FROM matters WHERE user_id IN (SELECT id FROM users WHERE auth_id LIKE ${like})`;
    await sql`DELETE FROM documents WHERE user_id IN (SELECT id FROM users WHERE auth_id LIKE ${like})`;
    await sql`DELETE FROM saved_searches WHERE user_id IN (SELECT id FROM users WHERE auth_id LIKE ${like})`;
    await sql`DELETE FROM judgment_annotations WHERE user_id IN (SELECT id FROM users WHERE auth_id LIKE ${like})`;
    await sql`DELETE FROM users WHERE auth_id LIKE ${like}`;
    await sql`DELETE FROM auth_user WHERE id LIKE ${like}`;

    // The matrix is the deliverable, not the pass count. Printed so a reviewer
    // reads what was actually attempted rather than trusting a green tick.
    const width = Math.max(...matrix.map((m) => m.resource.length), 8);
    console.log('\nTENANT ISOLATION MATRIX (USER_B against USER_A-owned rows)');
    console.log(['RESOURCE'.padEnd(width), 'OP'.padEnd(7), 'STATUS', 'RESULT'].join(' '));
    for (const m of matrix) {
      console.log(
        [m.resource.padEnd(width), m.op.padEnd(7), String(m.status).padEnd(6), m.result].join(' '),
      );
    }
    const fails = matrix.filter((m) => m.result === 'FAIL').length;
    const oracles = matrix.filter((m) => m.result === 'PASS_BUT_ORACLE').length;
    console.log(`\n${matrix.length} attempts · ${fails} FAIL · ${oracles} 403-instead-of-404\n`);
    await sql.end({ timeout: 5 });
  });

  it('anonymous callers reach no private surface at all', async () => {
    for (const path of ['/matters', '/documents', '/saved-searches', '/alerts', '/me']) {
      const r = await app.request(path);
      record(`anon ${path}`, 'LIST', r.status);
      assert.equal(r.status, 401, `${path} answered an anonymous caller with ${r.status}`);
    }
  });

  it('MATTER — read, write and its sub-collections are refused to a foreign user', async () => {
    const id = owned['matter']!;
    refused(
      'matter',
      'READ',
      (await app.request(`/matters/${id}`, { headers: hdr(B.token) })).status,
    );
    refused(
      'matter',
      'WRITE',
      (
        await app.request(`/matters/${id}`, {
          method: 'PATCH',
          headers: hdr(B.token),
          // A VALID body. An invalid one bounces at the validator and never
          // reaches the ownership check — see `record`.
          body: JSON.stringify({ status: 'archived' }),
        })
      ).status,
    );
    refused(
      'matter.events',
      'WRITE',
      (
        await app.request(`/matters/${id}/events`, {
          method: 'POST',
          headers: hdr(B.token),
          body: JSON.stringify({ eventType: 'note', eventDate: '2026-08-21', description: 'x' }),
        })
      ).status,
    );
    refused(
      'matter.authorities',
      'READ',
      (await app.request(`/matters/${id}/authorities`, { headers: hdr(B.token) })).status,
    );
    refused(
      'matter.shares',
      'READ',
      (await app.request(`/matters/${id}/shares`, { headers: hdr(B.token) })).status,
    );
    refused(
      'matter.briefings',
      'READ',
      (await app.request(`/matters/${id}/briefings`, { headers: hdr(B.token) })).status,
    );
  });

  it('MATTER SUB-OBJECTS — events and authorities are not mutable by a foreign user', async () => {
    const id = owned['matter']!;
    if (owned['event']) {
      refused(
        'matter.event.visibility',
        'WRITE',
        (
          await app.request(`/matters/${id}/events/${owned['event']}`, {
            method: 'PATCH',
            headers: hdr(B.token),
            body: JSON.stringify({ noteVisibility: 'shared' }),
          })
        ).status,
      );
    }
    if (owned['judgment']) {
      refused(
        'matter.authorities',
        'WRITE',
        (
          await app.request(`/matters/${id}/authorities`, {
            method: 'POST',
            headers: hdr(B.token),
            body: JSON.stringify({ judgmentId: owned['judgment'] }),
          })
        ).status,
      );
    }
    if (owned['authority']) {
      refused(
        'matter.authority',
        'DELETE',
        (
          await app.request(`/matters/${id}/authorities/${owned['authority']}`, {
            method: 'DELETE',
            headers: hdr(B.token),
          })
        ).status,
      );
      const [still] = await sql<{ n: string }[]>`
        SELECT count(*)::text AS n FROM matter_authorities WHERE id = ${owned['authority']}`;
      assert.equal(still!.n, '1', "USER_B's DELETE removed USER_A's matter authority");
    }
  });

  it('DOCUMENT CITATIONS — a foreign user cannot add or remove an authority on a draft', async () => {
    if (!owned['judgment']) return;
    refused(
      'document.citations',
      'WRITE',
      (
        await app.request(`/documents/${owned['document']}/citations`, {
          method: 'POST',
          headers: hdr(B.token),
          body: JSON.stringify({ judgmentId: owned['judgment'] }),
        })
      ).status,
    );
  });

  it('MATTER SHARING — a foreign user cannot invite themselves in', async () => {
    // The share path is the one place a matter is legitimately reachable by a
    // second identity, which makes it the highest-value target on this surface:
    // if USER_B can create a share, every ownership check downstream becomes
    // decorative.
    const r = await app.request(`/matters/${owned['matter']}/shares`, {
      method: 'POST',
      headers: hdr(B.token),
      body: JSON.stringify({ identifier: B.email }),
    });
    refused('matter.shares', 'WRITE', r.status);
  });

  it('MATTER LIST — A-owned ids never appear in B-owned listings', async () => {
    const r = await app.request('/matters', { headers: hdr(B.token) });
    assert.equal(r.status, 200);
    const body = JSON.stringify(await r.json());
    record('matter', 'LIST', body.includes(owned['matter']!) ? 200 : 404);
    assert.ok(!body.includes(owned['matter']!), "USER_A's matter id appeared in USER_B's list");
  });

  it('DOCUMENT — a generated draft is not readable, patchable or listable by a foreign user', async () => {
    const id = owned['document']!;
    refused(
      'document',
      'READ',
      (await app.request(`/documents/${id}`, { headers: hdr(B.token) })).status,
    );
    refused(
      'document',
      'WRITE',
      (
        await app.request(`/documents/${id}`, {
          method: 'PATCH',
          headers: hdr(B.token),
          body: JSON.stringify({
            paragraphs: [{ index: 0, text: 'overwritten by a stranger' }],
          }),
        })
      ).status,
    );
    const list = await app.request('/documents', { headers: hdr(B.token) });
    const body = JSON.stringify(await list.json());
    record('document', 'LIST', body.includes(id) ? 200 : 404);
    assert.ok(!body.includes(id), "USER_A's document id appeared in USER_B's list");
    // And the write must not have landed even if the status was permissive: a
    // handler can answer 404 and still have run its UPDATE.
    const [row] = await sql<{ generated_content: string }[]>`
      SELECT generated_content FROM documents WHERE id = ${id}`;
    assert.equal(row!.generated_content, 'privileged draft body');
  });

  it('BRIEFING — a matter briefing is not readable by a foreign user', async () => {
    const id = owned['briefing']!;
    refused(
      'briefing',
      'READ',
      (await app.request(`/briefings/${id}`, { headers: hdr(B.token) })).status,
    );
    refused(
      'briefing.opened',
      'WRITE',
      (await app.request(`/briefings/${id}/opened`, { method: 'POST', headers: hdr(B.token) }))
        .status,
    );
  });

  it('SAVED SEARCH — not readable, not deletable, and its feed is not reachable', async () => {
    const id = owned['savedSearch'];
    if (!id) return; // no saved search was created in this environment
    refused(
      'savedSearch.feed',
      'READ',
      (await app.request(`/saved-searches/${id}/feed`, { headers: hdr(B.token) })).status,
    );
    refused(
      'savedSearch',
      'DELETE',
      (await app.request(`/saved-searches/${id}`, { method: 'DELETE', headers: hdr(B.token) }))
        .status,
    );
    const [still] = await sql<{ n: string }[]>`
      SELECT count(*)::text AS n FROM saved_searches WHERE id = ${id}`;
    assert.equal(still!.n, '1', "USER_B's DELETE removed USER_A's saved search");
  });

  it('ANNOTATION — private notes on a public judgment stay private', async () => {
    const id = owned['annotation'];
    if (!id) return;
    // The judgment is public; the annotation is not. Listing annotations on the
    // same judgment as USER_B must not return USER_A's note text.
    const list = await app.request(`/judgments/${owned['judgment']}/annotations`, {
      headers: hdr(B.token),
    });
    const body = JSON.stringify(await list.json());
    record('annotation', 'LIST', body.includes('privileged annotation') ? 200 : 404);
    assert.ok(!body.includes('privileged annotation'), "USER_A's annotation leaked to USER_B");
    refused(
      'annotation',
      'DELETE',
      (await app.request(`/annotations/${id}`, { method: 'DELETE', headers: hdr(B.token) })).status,
    );
    const [still] = await sql<{ n: string }[]>`
      SELECT count(*)::text AS n FROM judgment_annotations WHERE id = ${id}`;
    assert.equal(still!.n, '1', "USER_B's DELETE removed USER_A's annotation");
  });

  it('ADMIN SEPARATION — an ordinary advocate reaches no admin surface, an admin does', async () => {
    const surfaces = [
      '/admin/users',
      '/admin/audit',
      '/admin/metrics',
      '/admin/platform',
      '/admin/citations',
    ];
    for (const path of surfaces) {
      const asAdvocate = await app.request(path, { headers: hdr(B.token) });
      record(`admin ${path}`, 'READ', asAdvocate.status, true);
      assert.equal(asAdvocate.status, 403, `${path} let an ordinary advocate in`);
    }
    // The positive control. Without it a middleware that refuses EVERYONE would
    // pass every assertion above and take the admin panel down silently.
    const asAdmin = await app.request('/admin/metrics', { headers: hdr(ADMIN.token) });
    assert.equal(asAdmin.status, 200, 'the admin role could not reach /admin/metrics');
  });

  it('USER ENUMERATION — the user list is admin-only and /me never answers for another id', async () => {
    const r = await app.request('/admin/users', { headers: hdr(B.token) });
    assert.equal(r.status, 403);
    // /me is derived from the token, never from a parameter — assert that a
    // parameter cannot steer it.
    const spoof = await app.request(`/me?userId=${A.userId}`, { headers: hdr(B.token) });
    const body = JSON.stringify(await spoof.json());
    record('me?userId=', 'READ', body.includes(A.email) ? 200 : 404);
    assert.ok(!body.includes(A.email), '/me answered for another user when given a query parameter');
  });

  it('TOKEN REPLAY — a token signed with the wrong secret is refused', async () => {
    const forged = await signAccessToken(
      { sub: A.authId, email: A.email },
      'a-different-secret-entirely',
    );
    const r = await app.request('/matters', { headers: hdr(forged) });
    record('forged token', 'LIST', r.status);
    assert.equal(r.status, 401, 'a token signed with an unknown secret was accepted');
  });
});
